### ISSUE TITLE
Use all formatters

### ISSUE THREAD

**Issue by dzintars** [konapun/dotfiles#10]
First of all thank you for sharing your dots. Taking a huge inspiration on Efm file organization. Really like it. 🥇 
Now back to business - you have this line:
https://github.com/konapun/dotfiles/blob/b1d690eb2e328e8929093c50ad2b08d3a68b7d05/nvim/lua/config/lspconfig.lua#L52
Have considered to use `formatting_seq_sync({}, 1000)` which would allow to use all formaters?

**Comment by konapun** [comment]
I'll give that a try, thanks!
